### ISSUE TITLE
Question about Digest auth support in EasyRdf

### ISSUE THREAD

**Issue by ashepherd** [djevans/sparql_update_indexer#2]
Hey! Thanks for letting me know about this module. Looks great! 

Do you know if EasyRdf support digest authentication to the SPARQL endpoint? Our Virtuoso endpoint is publicly available, but also has an authed endpoint (/sparql-auth that supports digest authentication). Do you think I could use EasyRdf to do that?

**Comment by djevans** [comment]
Hi,

You can use `EasyRdf_Http::setDefaultHttpClient()` to get EasyRdf to use a different HTTP client, but as you can see from the snippet below, your choice is quite restricted.

``` php
public static function setDefaultHttpClient($httpClient)
{
    if (!is_object($httpClient) or
        !($httpClient instanceof Zend_Http_Client or
          $httpClient instanceof EasyRdf_Http_Client)) {
        throw new InvalidArgumentException(
            "\$httpClient should be an object of class Zend_Http_Client or EasyRdf_Http_Client"
        );
    }
    return self::$defaultHttpClient = $httpClient;
}
```

The version of Zend_Http_Client from Zend Framework 1.12 doesn't support digest authentication, and I'm not sure that Zend Framework 2 does either, as of v2.4 at least.

I think the best option in this case would be to use another library ([Guzzle](http://guzzle3.readthedocs.org/http-client/client.html), for example) and extend EasyRdf_Http_Client to wrap its client class's functionality.

Hope this helps!

**Comment by ashepherd** [comment]
Great thanks!
